# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Biol415
tagline:          'Plant Evolution'
description:      'Evolutionary Processes in Plants'
url:              /
baseurl:          /

author:
  name:           'Gregory Owens'
  url:            https://twitter.com/Greg_Owens

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ubcbiol415/ubcbiol415.github.io


